[View in Colaboratory](https://colab.research.google.com/github/sxqqslf/TensorflowDaily/blob/master/ResearchAndExpermentation/eagerExecution.ipynb)

In [1]:
import tensorflow as tf

tf.enable_eager_execution()

1.12.0-rc1


In [3]:
print(tf.add(1,2))
print(tf.add([1,2], [3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))
print(tf.encode_base64("hello world"))

print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


In [5]:
x = tf.matmul([[1]], [[2,3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [7]:
import numpy as np
ndarray = np.ones([3,3])

print("TesnsorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)

print("And Numpy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

TesnsorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And Numpy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [9]:
x = tf.random_uniform([3, 3])

print("Is there a GPU available: "),
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0: "),
print(x.device.endswith('GPU:0'))
print(x.device) 

Is there a GPU available: 
False
Is the Tensor on GPU #0: 
False
/job:localhost/replica:0/task:0/device:CPU:0


In [10]:
def time_matmul(x):
  %timeit tf.matmul(x, x)
  
print("On CPU:")
with tf.device("CPU:0"):
  x = tf.random_uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)

if tf.test.is_gpu_available():
  with tf.device("GPU:0"):
    x = tf.random_uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:
10 loops, best of 3: 20.4 ms per loop


In [15]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
  Line 2
  Line 3
  """)
ds_file = tf.data.TextLineDataset(filename)

ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.batch(2)

print('Elements of ds_tensors:')
for x in ds_tensors:
  print(x)
  
print('\nElements in ds_file:')
for x in ds_file:
  print(x)

Elements of ds_tensors:
tf.Tensor([4 9], shape=(2,), dtype=int32)
tf.Tensor([ 1 16], shape=(2,), dtype=int32)
tf.Tensor([25 36], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line 1' b'  Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'  Line 3' b'  '], shape=(2,), dtype=string)


In [28]:
# shuffle buffer_size understanding https://juejin.im/post/5b855d016fb9a01a1a27d035
a = np.array(range(50))
data = tf.data.Dataset.from_tensor_slices(a)
data = data.shuffle(5).batch(5)
for x in data:
  print(x)


tf.Tensor([2 3 6 4 7], shape=(5,), dtype=int64)
tf.Tensor([ 5  0  9 10  8], shape=(5,), dtype=int64)
tf.Tensor([ 1 12 11 17 18], shape=(5,), dtype=int64)
tf.Tensor([13 16 15 22 23], shape=(5,), dtype=int64)
tf.Tensor([21 14 25 26 24], shape=(5,), dtype=int64)
tf.Tensor([20 19 28 31 32], shape=(5,), dtype=int64)
tf.Tensor([33 30 34 36 35], shape=(5,), dtype=int64)
tf.Tensor([37 39 38 40 42], shape=(5,), dtype=int64)
tf.Tensor([44 45 27 47 29], shape=(5,), dtype=int64)
tf.Tensor([41 49 46 43 48], shape=(5,), dtype=int64)
